name: gamestoreapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.8
  firebase_ui_auth: ^1.11.0
  flutter:
    sdk: flutter
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
